name: CI

on:
  push:
    branches:
        - master
        - 'ci-*'
  pull_request: {}

jobs:
  # Separate "fmt" and "build" workflows so that lint failure don't block tests
  # from running. See also "continue-on-error" feature request:
  # https://github.community/t/continue-on-error-allow-failure-ui-indication/16773/11
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Verify formatting
        run: go fmt ./... | diff -u /dev/null -

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check out TensorBoard protos
        uses: actions/checkout@v2
        with:
          repository: tensorflow/tensorboard
          ref: 3010b2c6afba6abbf68cf3f759c31d7b70d8daf9
          path: ./tmp/tensorboard

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.13.0'

      - name: Bootstrap Go modules
        run: ./build_protos.sh --bootstrap

      - name: Install protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          which protoc-gen-go

      - name: Compile proto definitions to Go source code
        run: ./build_protos.sh ./tmp/tensorboard

      - name: Remove TensorBoard repository  # to avoid building anything in it
        run: rm -rf ./tmp/tensorboard

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -count=32 ./...
