name: CI

on:
  push:
    branches:
        - master
        - 'ci-*'
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
